[package]
name = "image_to_html"
version = "0.1.0"
authors = ["insomnyawolf <insomnyawolf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"